name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.8]
        pytest-version: ["<5.4", ">6"]
        exclude:
          - python-version: 2.7
            pytest-version: ">6"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Pytest ${{ matrix.pytest-version }}
      run: pip install "pytest${{ matrix.pytest-version }}"
    - name: Install
      run: python setup.py develop
    - name: Test
      run: |
        ! py.test --eradicate setup.py
        py.test --eradicate pytest_eradicate.py